-- AlterTable
ALTER TABLE "Match" ALTER COLUMN "teamAScore" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "teamBScore" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Result" ALTER COLUMN "finalScoreA" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "finalScoreB" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ScoreEvent" ALTER COLUMN "points" SET DEFAULT 0,
ALTER COLUMN "points" SET DATA TYPE DOUBLE PRECISION;
