name: Deploy to Production

on:
  push:
    branches:
      - master # or main, depending on your primary branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Remote Deployment Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            /var/www/app/deploy.sh
